name: Continuous Integration and Deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: PokemonTest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST_TEST: localhost
      DB_PORT_TEST: 5432
      DB_NAME_TEST: PokemonTest
      DB_USER_TEST: postgres
      DB_PASSWORD_TEST: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: PokemonTest
      DB_USER: postgres
      DB_PASSWORD: postgres
      EMAIL_LOGIN: t
      EMAIL_PASSWORD: t
      FTP_HOST: ftp
      FTP_PORT: 21
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      AUTH_SECRET: 2
      MANAGER_SECRET: p
      RESET_SECRET: p
      VERIFICATION_SECRET: v
      CLIENT_ID: 6
      CLIENT_SECRET: G
      STATE_SECRET: g

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.6"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -v -s tests/

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push with Docker Compose
        run: |
          docker build -t fastapi-pokeback .
          docker tag fastapi-pokeback:latest thenorthlord/fastapi-pokeback:latest
          docker push thenorthlord/fastapi-pokeback:latest
